Portfolio project: Desktop version
Kalunge/portfolio-project pull request #4
Opened 2021-07-14 21:21 UTC by Kalunge

## Portfolio project: Desktop version
in this milestone I
- Added the Desktop version.

2021-07-14 22:21 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️ 

## Hello @Kalunge ✋🏼  Your project is great. You are almost done. However there are some issues you should fix. Please fix them then your project will be approved.

### 💯  Nice to have 💯
 
- Your git flow is correct
- You set up linter files and no errors.
- You implement media queries in css.

### ♻️ Request changes ♻️

_**Check the comment about that  under the review.**_


### OPTIONAL SUGGESTIONS

#### These are optional 

- [ ]  Instead of using pictures for icons you can use icons from [font-awesome](https://fontawesome.com/start). 

- [ ] For DRY css you can  combine duplicate properties. You can create class `.d-flex { display: flex}` and use this class in html file.

- For more information about DRY principles you can check this [article](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/) 

- Also you can refresh your knowledge about "html and css best practices" in [curriculum](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

### Cheers and Happy coding! 💻 👏
![cat on laptop](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

2021-07-14 22:21 UTC, ahmetbozaci commented on index.html
> +            <h3 class="desktop">Portforlio</h3>
- [ ] It should  be "Portfolio". Please update this.
- [ ] You should use same font from design. Original design's font is not that. You should use this font  [Poppins.](https://fonts.google.com/specimen/Poppins) You can  check this [article](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts) for how to use google fonts.

2021-07-14 22:21 UTC, ahmetbozaci commented on styles.css
> +    display: flex;
### OPTIONAL
- [ ] For DRY css you can combine duplicate properties. 
You can create class `.d-flex { display: flex}` and use this class in html file.

- For more information about DRY principles you can check this [article](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/)

2021-07-14 22:21 UTC, ahmetbozaci commented on index.html
> +            <h1>My Logo</h1>
- [ ] You  should delete `h1` tag. You can keep text wrapped by `a` tag . You should only use one `<h1>` per page - this should represent the main heading/subject for the whole page.

2021-07-14 22:21 UTC, ahmetbozaci commented on index.html
> +          <li><a href="#"><img src="./img//vector.svg" alt=""></a></li>
### OPTIONAL

- [ ] Instead of using pictures for icons you can use icons from [font-awesome](https://fontawesome.com/start).

2021-07-14 22:21 UTC, ahmetbozaci commented on index.html
> +      </section>
- [ ] You should stick the design. Your design background image is different. Please fix this.
- [ ] End of the page is empty. I can scroll down.You should fix this.

**Original design:**
![image](https://user-images.githubusercontent.com/38635158/125698480-52978b59-fac9-4c9d-b270-b7b770c9014e.png)
___
**Your design:**
![image](https://user-images.githubusercontent.com/38635158/125699002-d64bdc6a-dd5c-4e4f-9eaa-072465ca615d.png)

2021-07-14 22:21 UTC, ahmetbozaci commented on index.html
> +          <br>
- [ ] Below 1000px width contact section broken. Please fix this.

![image](https://user-images.githubusercontent.com/38635158/125699295-542f85f7-d9b9-43ad-a22e-cf529b3bafce.png)

2021-07-14 22:21 UTC, ahmetbozaci commented on index.html
> +      </section>
- [ ] Below 1000px width about section's align is broken. ıt should be center like language section.

You should fix this.
![image](https://user-images.githubusercontent.com/38635158/125699620-f44efb86-d87d-43c7-9064-69a22fb86e1c.png)

2021-07-15 09:05 UTC, Kalunge commented on index.html
> +            <h3 class="desktop">Portforlio</h3>
Thanks for your recommendation. worked on the required section and will continue working on the optional after programme hours

2021-07-15 09:40 UTC, carlos-ssh requested changes
Hi @Kalunge , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-15 09:40 UTC, carlos-ssh commented on index.html
> +          project <br> that needs coding. I’d  love to help with it </p>
- Kindly center your p tag in your view.

2021-07-15 09:40 UTC, carlos-ssh commented on styles.css
>  .me {
- Kindly remove empty classes.
- Try to implement in your code DRY methodology. In example:
``` 
.role {
  font-family: Poppins, sans-serif;
  font-style: normal;
  font-weight: 600;
  font-size: 13px;
  line-height: 16px;
  color: #7a869a;
  list-style-type: disc;
}

.time {
  font-family: Poppins, sans-serif;
  font-style: normal;
  font-weight: 600;
  font-size: 13px;
  line-height: 16px;
  color: #7a869a;
  list-style-type: disc;
}
```

2021-07-15 09:40 UTC, carlos-ssh commented on styles.css
> +    display: flex;
- Keep working with the DRY requirements from your last reviewer.

2021-07-15 10:47 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi @Kalunge, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of  code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-07-15 10:49 UTC, merged